commercetools/commercetools-ios-sdk

Commercetools.xcodeproj/project.pbxproj, README.md, Source/Commercetools.swift, Source/Config.swift, Source/Log.swift
@cneijenhuis @lauraluiz  Centralized configuration handling, API hosts, and all client params, logging common errors and problems
=> Closes #1, closes #3, related #6 Configuration handling

.travis.yml, Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools.xcscheme, README.md
@cneijenhuis @lauraluiz Closes #18 - Added travis configuration, CI executes both for master and all other PR / branches.
=> Setup travis

Commercetools.xcodeproj/project.pbxproj, CommercetoolsTests/DeleteEndpointTests.swift, Source/Endpoint/ByIdEndpoint.swift, Source/Endpoint/CreateEndpoint.swift, Source/Endpoint/DeleteEndpoint.swift, Source/Error.swift
@cneijenhuis @lauraluiz - Support for delete endpoints
=> Closes #11 Support for delete endpoints

Commercetools.xcodeproj/project.pbxproj, CommercetoolsTests/UpdateEndpointTests.swift, Source/Endpoint/UpdateEndpoint.swift
@cneijenhuis @lauraluiz - Support for update endpoints
=> Closes#10 Support for update endpoints

Commercetools.xcodeproj/project.pbxproj, CommercetoolsTests/QueryEndpointTests.swift, Source/Endpoint/QueryEndpoint.swift
=> Closes #10 Support for query endpoints

Commercetools.xcodeproj/project.pbxproj, CommercetoolsTests/ByKeyEndpointTests.swift, Source/Endpoint/ByKeyEndpoint.swift
@cneijenhuis @lauraluiz Support for by key endpoints
=> Closes #22 Support for by key endpoints

Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools.xcscheme, CommercetoolsTests/Core/QueryEndpointTests.swift, CommercetoolsTests/Endpoints/CustomerTests.swift, Source/AuthManager.swift, Source/Commercetools.swift, Source/Endpoints/Customer.swift
@cneijenhuis @lauraluiz Advanced /me endpoint functionality with tests
@cneijenhuis - as agreed, tests for password reset, and email verification, have are being skipped during travis CI execution, and we will include client credentials with higher scope in CI environment variables + refactor tests as a part of a separate PR.
=> Closes #15 Advanced /me endpoint functionality with tests

Commercetools.xcodeproj/project.pbxproj, Source/Endpoints/Order.swift
@cneijenhuis @lauraluiz - Support for /me/orders endpoint
=> Closes #13 Support for /me/orders endpoint

Commercetools.xcodeproj/project.pbxproj, CommercetoolsTests/Core/QueryEndpointTests.swift, CommercetoolsTests/Endpoints/ProductProjectionTests.swift, Source/Core/QueryEndpoint.swift, Source/Endpoints/Customer.swift, Source/Endpoints/ProductProjection.swift
@cneijenhuis @lauraluiz - Support for project projections endpoint functionality
=> Closes #16 Basic project projections endpoint functionality

README.md, Source/Endpoints/Customer.swift, Source/Endpoints/ProductProjection.swift, Tests/Endpoints/ProductProjectionTests.swift
@cneijenhuis @lauraluiz Support for product projection search
=> Closes #17 Support for product projection search

README.md, Source/Core/UpdateEndpoint.swift, Source/Endpoints/ProductProjection.swift, Tests/Endpoints/ProductProjectionTests.swift
@cneijenhuis @lauraluiz Support for product projection suggestions
=> Closes #49 Product projection suggestions

Commercetools.xcodeproj/project.pbxproj, README.md, Source/Endpoints/Category.swift, Source/Endpoints/ProductType.swift
@cneijenhuis @lauraluiz Support for categories endpoint
=> Issue/#50 Categories endpoint

Commercetools.xcodeproj/project.pbxproj, Source/Endpoints/ProductType.swift
@cneijenhuis @lauraluiz Support for product type endpoint
=> Closes #51 Support for product type endpoint

Source/Config.swift, Source/TokenStore.swift, Tests/Core/ByIdEndpointTests.swift, Tests/Core/ByKeyEndpointTests.swift, Tests/Core/CreateEndpointTests.swift, Tests/Core/DeleteEndpointTests.swift, Tests/Core/QueryEndpointTests.swift, Tests/Core/UpdateByKeyEndpointTests.swift, Tests/Core/UpdateEndpointTests.swift, Tests/Endpoints/CustomerTests.swift, Tests/Endpoints/ProductProjectionTests.swift, Tests/XCTestCase+Configuration.swift
Added project key to keychain dictionary keys and updated tests.
=> Closes #60 Added project key to keychain dictionary keys

.travis.yml, README.md, Source/AuthManager.swift, Source/Commercetools.swift, Source/Config.swift, Source/TokenStore.swift, Tests/AuthManagerTests.swift, Tests/CommercetoolsTestConfig.plist, Tests/XCTestCase+Configuration.swift
Documentation + more tests to come...
=> Closes #58 Anonymous session support

README.md
Updated docs to align with Swift 3 updates, and endpoints supporting response and draft models
=> Updated docs to align with Swift 3 updates, and endpoints supporting response and draft models

Source/Endpoints/ProductProjection.swift, Source/Models/Address.swift, Tests/Endpoints/ProductProjectionTests.swift
Closes #92 Conform ProductProjection to ByKeyEndpoint
Closes #93 Add externalId to the Address struct
=> Closes #92 Conform ProductProjection to ByKeyEndpoint , Closes #93 Add externalId to the Address struct

Commercetools.podspec, Commercetools.xcodeproj/project.pbxproj, Podfile, README.md, Source/Commercetools.h, Source/Commercetools.swift, Source/Config.swift, Source/TokenStore.swift, Tests/CommercetoolsTestConfig.plist
I will update the docs with instructions and added config params for when using the `WatchConnectivity`, but you can feel free to look at the code itself.
I'm also using this feature to build Sunrise watch app, so in case I stumble across any problems, I'll incorporate solutions here, before merging.
=> Closes #99 Use WatchConnectivity to share tokens between iOS and watchOS keychains

README.md
Updated `README.md` with WatchConnectivity feature we added.
=> Closes #101 Document WatchConnectivity SDK features

Commercetools.xcodeproj/project.pbxproj, Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools iOS.xcscheme, Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools macOS.xcscheme, Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools tvOS.xcscheme, Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools watchOS.xcscheme, Source/Models/Models.swift
`geoLocation` field has been added to the `Channel` struct, as well as computed properties `location`, which is returned from the  GeoJSON Geometry `Point` type.
@cneijenhuis , @lauraluiz LMK if you agree with this?
=> Closes #107 Add geoLocation field to Channel model

Source/Endpoints/Category.swift
Trivial change; I guess we should merge this one after the feature has been deployed.
=> Closes #111 Add support for category assets

Source/TokenStore.swift
Improved token sync with WatchConnectivity: In case you had your iOS app installed before connecting the watch (or simply installed the watch app at a later time), you had to open the iOS app in order for the tokens to be synced. This is no longer the case.
=> Improve WatchConnectivity communication

Source/ProductProjection.swift
=> Fix class documentation

Source/Cart.swift, Source/Category.swift, Source/Commercetools.swift, Source/CreateEndpoint.swift, Source/Customer.swift, Source/Endpoint.swift, Source/Models.swift, Source/Order.swift, Source/ProductProjection.swift, Source/ProductType.swift, Source/QueryEndpoint.swift, Source/Result.swift, Source/ShippingMethod.swift, Tests/AuthManagerTests.swift, Tests/Endpoints/CartTests.swift, Tests/Endpoints/CustomerTests.swift, Tests/Endpoints/ProductProjectionTests.swift, Tests/Endpoints/ProjectSettingsTests.swift, Tests/Endpoints/ShippingMethodTests.swift
This is the first part related to issue #140 - this PR is targeting main endpoints, and the changes for other models will come in a next one. At some point, we'll also shall remove `ObjectMapper` (issue #142 ).
=> Related #140 Update models for main endpoints

.travis.yml, Commercetools.podspec, Commercetools.xcodeproj/project.pbxproj, Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools iOS.xcscheme, Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools macOS.xcscheme, Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools tvOS.xcscheme, Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools watchOS.xcscheme, Podfile, Source/Cart.swift, Source/Category.swift, Source/Commercetools.swift, Source/CreateEndpoint.swift, Source/Customer.swift, Source/Endpoint.swift, Source/Models.swift, Source/Order.swift, Source/ProductProjection.swift, Source/ProductType.swift, Source/QueryEndpoint.swift, Source/Result.swift, Source/ShippingMethod.swift, Source/TokenStore.swift, Source/UpdateEndpoint.swift, Tests/AuthManagerTests.swift, Tests/Endpoints/CartTests.swift, Tests/Endpoints/CustomerTests.swift, Tests/Endpoints/ProductProjectionTests.swift, Tests/Endpoints/ProjectSettingsTests.swift, Tests/Endpoints/ShippingMethodTests.swift
This is the second PR regarding the issue #140 - the last one will be related to refactoring update actions. @cneijenhuis I suggest you look at the diff right after we merge #143
=> Related #140 Update all other models

Source/Models.swift, Source/ShippingMethod.swift, Tests/Endpoints/CartTests.swift, Tests/Endpoints/ShippingMethodTests.swift
=> Conform ShippingMethod to ByKeyEndpoint protocol

Source/Models.swift
My code changes are  pretty much final, but some tests are not passing ATM, because the search endpoint isn't returning all mandatory fields for `BasePrice`. That should be fixed hopefully soon, but you can check out the code in the meantime.
=> Support for HighPrecisionMoney

README.md
Hi.
I've fixed a few things that got out of sync in the documentation.
=> Fix Cart creation and update sample code

README.md
Use Commercetools.signUpCustomer() instead of Customer.signup() because the latter is internal
=> Use Commercetools.signUpCustomer() instead of Customer.signup()

Source/Models.swift
Updated SDK to latest platform releases:
https://docs.commercetools.com/release-notes.html#releases-2018-11-06-custom-line-item-return-item
https://docs.commercetools.com/release-notes.html#releases-2018-11-15-zone-key
https://docs.commercetools.com/release-notes.html#releases-2018-12-19-reference-by-key
https://docs.commercetools.com/release-notes.html#releases-2019-01-04-ref-channels-by-key
=> Platform updates - Nov to Jan

Commercetools.xcodeproj/project.pbxproj, README.md, Source/Cart.swift, Source/Models.swift, Source/Order.swift, Source/Store.swift, Tests/CommercetoolsTestConfig.plist, Tests/Endpoints/StoreTests.swift
Introduced `Store` endpoint which conforms to `QueryEndpoint`, `ByIdEndpoint`, and  `ByKeyEndpoint` protocols, which aligns with mobile client scope.
@cneijenhuis as usual, any feedback is welcome 👍
=> Support for stores

Commercetools.xcodeproj/project.pbxproj, README.md, Source/CategoryRecommendations.swift, Source/Models.swift, Tests/MachineLearningEndpoints/CategoryRecommendationsTests.swift
@amagrabi any suggestions / comments are more than welcome ☺️
=> Support for CategoryRecommendations ML Endpoint

Source/Models.swift
proposed solution for issue #182
=> custom fields in Address
