commercetools/commercetools-ios-sdk

.travis.yml
scripts/deploy.sh

@cneijenhuis @lauraluiz - this enabled us to have automatic release on CocoaPods. After pushing a new tag, travis ci will execute `pod trunk push`. I have already setup the necessary `COCOAPODS_TRUNK_TOKEN` environment variable in the travis config for this project.

Closes #19 automatically release on CocoaPods when we use git tag

---

CommercetoolsTests/ByIdEndpointTests.swift
CommercetoolsTests/QueryEndpointTests.swift
CommercetoolsTests/UpdateEndpointTests.swift

@cneijenhuis @lauraluiz In our tests, we've been using UUID references, which needed to be removed, and tests refactored to run without them. We addressed it in this issue.

Closes #36 Updated tests not to use object UUIDs

---

Commercetools.xcodeproj/project.pbxproj
Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools.xcscheme
CommercetoolsTests/UpdateByKeyEndpointTests.swift
Source/Endpoint/QueryEndpoint.swift
Source/Endpoint/UpdateByKeyEndpoint.swift

@cneijenhuis @lauraluiz - Support for update by key endpoints
I've left `UpdateByKeyEndpointTests`. The only difference compared to other tests, is that is has overridden `setupTestConfiguration` which sets configuration containing appropriate scope in order to be able to test updates to product-types endpoint.

Closes #23 Support for update by key endpoints

---

Source/Core/QueryEndpoint.swift

@cneijenhuis @lauraluiz - Now we're using encoding provided by Alamofire, after @cneijenhuis updated the API to support array params in the URL with `[]` suffix.

Closes #44 Refactored query endpoint after API update

---

Commercetools.xcodeproj/xcshareddata/xcschemes/Commercetools.xcscheme
CommercetoolsTests/Core/UpdateByKeyEndpointTests.swift
CommercetoolsTests/Endpoints/CustomerTests.swift
CommercetoolsTests/XCTestCase+Configuration.swift

@cneijenhuis @lauraluiz - as agreed, our tests which need higher scope are now using client credentials from the environment variables. Those are set in Travis and hidden, so they're not displayed in the output log.

Closes #43 Refactor tests which require higher scope

---

Commercetools.xcodeproj/project.pbxproj
README.md
Source/AuthManager.swift
Source/Endpoints/ActiveCart.swift
Source/Endpoints/Cart.swift
Tests/Endpoints/CartTests.swift

The reason to introduce another class - `ActiveCart` - was to accommodate our endpoints structure. If our API path was `me/carts/active` instead of `me/active-cart` we could've done it without this additional class.
I also added static method `active` to the original `Cart` class, as a shortcut for easier access, which practically gives the user ability to access active cart with `Cart.active(...)`

Closes #62 Supoprt active cart

---

Commercetools.xcodeproj/project.pbxproj
README.md
Source/AuthManager.swift
Source/CTError.swift
Source/Commercetools.swift
Source/Endpoints/Customer.swift
Source/Models/AnonymousCartSignInMode.swift
Tests/AuthManagerTests.swift
Tests/Core/ByIdEndpointTests.swift
Tests/Core/CreateEndpointTests.swift
Tests/Core/DeleteEndpointTests.swift
Tests/Core/UpdateEndpointTests.swift
Tests/Endpoints/CartTests.swift
Tests/Endpoints/CustomerTests.swift

What we've done in this issue:
- Added `activeCartSignInMode: AnonymousCartSignInMode?` to the `AuthManager`'s `login` method;
- Added `login` method to the `Customer` endpoint, which can be explicitly used by the user in order to invoke carts and orders migration from the anonymous user (this happens automatically on the API side for sign up);
- Since the API doesn't automatically migrate carts and orders when there's no sign up, just login, we're doing that in the SDK. From the users perspective, it's enough to invoke `AuthManager`'s `login` method, and we'll perform `me/login` request, and obtain access and refresh token afterwards.
- Added tests which cover cart migration for logging in the existing user, and another to cover migration for new user (on sign up).

Closes #87 Add anonymous cart sign in mode

---

README.md
Source/AuthManager.swift
Source/Config.swift
Source/TokenStore.swift

In situations where the app using Commercetools SDK has extensions (such as today extension, notification content extension, etc), we want to enable our users to seamlessly use endpoints from the SDK in those extensions with the same auth tokens.
Common use cases:
- An app has a rich notification, which needs to retrieve an object from our API in order to display the rich content;
- An app has a today widget, which would like to show an overview of reservations ready for pickup, etc;
In any of those cases, the user has previously logged in using the app, but since the app and the extension run in a different sandbox, the extension wouldn't be able to get the data needed from the API, because it doesn't contain proper auth tokens.
The solution for this problem is to allow SDK users to …

Closes #89 Add config option for keychain sharing

---

Source/Endpoints/ProductProjection.swift
Tests/Endpoints/ProductProjectionTests.swift

I've also added `fuzzyLevel` parameter, which was missing from earlier implementation.

Closes #96 Add markMatchingVariants to the ProductProjection search method

---

Source/Core/Endpoint.swift

Just a minor update to the UserAgent method  - now we will be able to see the actual platform / OS that is using the Swift SDK to communicate with the commercetools platform.

Closes #102 UserAgent headers for newly added platforms

---

Source/Endpoints/Customer.swift
Source/Models/Models.swift

@cneijenhuis - I've added 4 new update actions: `addShippingAddressId`, `addBillingAddressId`, `removeShippingAddressId`, `removeBillingAddressId`.
They seem to be working with access tokens with _mobile scope_ and `/me` endpoint. 👍

Closes #105 Add shippingAddressIds and billingAddressIds to the Customer endpoint

---

Source/Endpoints/Customer.swift

This can be handy, in cases where customer custom type contains references to other objects, like in Sunrise example, we keep `myStore` channel ID. It'd be better to retrieve complete store details (`channel` object), along with user profile on my accounts page (`expansion = ["custom.fields.myStore"]`).

Closes #108 Add expansion parameter to the customer profile endpoint

---

Package.swift
Source/Endpoints/Cart.swift
Source/Models/Models.swift
Tests/Endpoints/CartTests.swift

Even though we don't have `taxRoundingMode` documented in the [MyCartDraft](http://dev.commercetools.com/http-api-projects-me-carts.html#mycartdraft), specifying the rounding mode when using `me/carts` endpoint works properly.
However, the `changeTaxRoundingMode` update action does not work.

Closes #114 Add taxRoundingMode field to Cart and CartDraft

---

Source/Endpoints/ProductProjection.swift
Tests/Endpoints/ProductProjectionTests.swift

I noticed this while implementing Sunrise iOS POP where  we need to filter for the products available in "my store" which match the selected category.

Closes #117 Add support for multiple filters for product projection search

---

Source/Config.swift

I think this should be sufficient for both the Sunrise configurable projects + config for scripts using the SDK via SPM.

Add public modifier for the dictionary config initializer

---

Commercetools.xcodeproj/project.pbxproj
Source/Endpoint.swift
Source/Models.swift
Source/Result.swift
Source/ShippingMethod.swift
Tests/AuthManagerTests.swift
Tests/Endpoints/ShippingMethodTests.swift

Up until now, we didn't have to to handle responses from the API which contain arrays as root JSON objects. `Result` and `Endpoint` have been changed to enable array parsing when retrieving the list of shipping methods for a cart, or a location.
Tests for this endpoint will be added shortly after the permissions are updated.

Closes #126 Add ShippingMethod endpoint support

---

Source/Commercetools.swift
Source/ProductProjection.swift
Tests/Endpoints/ProductProjectionTests.swift

Found this one out while implementing the localized voice search in Sunrise.

Closes #133 Use languageCode instead of locale identifier for product projection search

---

README.md
Source/Models.swift

Just added price tiers, even though the mobile clients won't be setting them for a product, it is possible the clients would want to show information retrieved from the tiers array on the POP / PDP (e.g get X items for XX amount of money, instead of XXX).

Add price tiers

---

Commercetools.podspec
Podfile
Source/ActiveCart.swift
Source/AuthManager.swift
Source/ByIdEndpoint.swift
Source/ByKeyEndpoint.swift
Source/Cart.swift
Source/Commercetools.swift
Source/CreateEndpoint.swift
Source/Customer.swift
Source/DeleteEndpoint.swift
Source/Endpoint.swift
Source/GraphQL.swift
Source/ProductProjection.swift
Source/QueryEndpoint.swift
Source/ShippingMethod.swift
Source/UpdateByKeyEndpoint.swift
Source/UpdateEndpoint.swift
Tests/Endpoints/CustomerTests.swift

The `Alamofire` has been removed as a dependency, but the `Endpoint` extension will slightly change again when we remove the `ObjectMapper` in favor of Swift 4 `Codable`.

Remove Alamofire

---

Source/Models.swift
Source/ShippingMethod.swift

While going through release notes, I've identified a few items which should be added to the Swift SDK, so I grouped them in this PR.

Add ExternalAmount to TaxMode, predicate to ShippingMethod & shippingMethodState to ShippingInfo

---

Source/Models.swift
Tests/Endpoints/CartTests.swift

Added a custom field to the DiscountCode, and tested it by expanding the `discountCodes` from the `Cart` response.

Add a custom field to the DiscountCode

---

README.md

Hi.
I've corrected a few typos in README.md that scratched my eyes while I was reading the documentation.
Cheers.

Fix spelling under `Consuming Commercetools Endpoints` and remove `Project settings` excessive line

---

Source/AuthManager.swift
Source/CTError.swift
Source/Endpoint.swift
Tests/AuthManagerTests.swift

@cneijenhuis - have a look if you get a chance, basically now the SDK will recover if the access tokens were dropped. Added 2 test cases and tested using the client (i.e iOS app).

Closes #161 Support recovering from invalid access token

---

Source/Endpoint.swift

`+` character is valid in a query string, which is stated in the documentation: https://developer.apple.com/documentation/foundation/nsurlcomponents/1407752-queryitems
However, from W3C recommendations for URI addressing (
https://www.w3.org/Addressing/URL/4_URI_Recommentations.html):
_Within the query string, the plus sign is reserved as shorthand notation for a space. Therefore, real plus signs must be encoded._
This PR updates generic method used for generating `URLRequest` used throughout the SDK.

Percent encode plus sign in URL query params

---

Source/AuthManager.swift
Source/Endpoint.swift
Source/ProductProjection.swift
Source/QueryEndpoint.swift

This PR adds support for creating `URLRequests` using `application/x-www-form-urlencoded` `Content-Type`.
`application/x-www-form-urlencoded` is now used for all auth related requests, as well as `ProductProjection` `search` endpoint.

Use application/x-www-form-urlencoded for auth and search

---

Source/ByIdEndpoint.swift
Source/ByKeyEndpoint.swift
Source/Cart.swift
Source/Commercetools.swift
Source/CreateEndpoint.swift
Source/Customer.swift
Source/DeleteEndpoint.swift
Source/Endpoint.swift
Source/GraphQL.swift
Source/Order.swift
Source/ProductProjection.swift
Source/QueryEndpoint.swift
Source/ShippingMethod.swift
Source/UpdateByKeyEndpoint.swift
Source/UpdateEndpoint.swift
Tests/PlatformEndpoints/CustomerTests.swift
Tests/PlatformEndpoints/StoreTests.swift

Added the following methods for the `Cart`:
- Get a Cart in a Store by ID
- Get Active Cart in a Store by ID
- Query Carts in a Store
- Create a Cart in a Store
- Update a Cart in a Store
- Delete a Cart in a Store
Added the following methods for the `Order`:
- Get Order in a Store by ID
- Query Orders in a Store by ID
- Create Order in a Store from a Cart

Support for in-store carts and orders

---

README.md
Source/AuthManager.swift
Source/Commercetools.swift
Source/TokenStore.swift
Tests/AuthManagerTests.swift
Tests/PlatformEndpoints/StoreTests.swift
Tests/XCTestCase+Configuration.swift

Closes #172 Support for external OAuth tokens

---

.travis.yml
README.md
Source/AuthManager.swift
Source/Cart.swift
Source/Commercetools.swift
Source/Config.swift
Source/Customer.swift
Source/Endpoint.swift
Source/Order.swift
Source/UpdateEndpoint.swift
Tests/PlatformEndpoints/CustomerTests.swift

Added support for in-store helpers available for the me endpoints for the customer.
Currently, the client needs to specify the `storeKey` with every call to any of the store-specific methods. @cneijenhuis do you think the SDK should perhaps have a `store` property, and once set, include it automatically in all store-specific subsequent requests?

Closes #177 Support for Customer Profile in a Specific Store
